services:
  cafe-mongo-service:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  cafe-auth-service:
    build: ./auth-api
    image: hautrank2/cafe-auth:1
    environment:
      TOKEN_KEY: 'doi-chuoi-nay-di'
      ADMIN_EMAIL: 'admin@cafe.local'
      ADMIN_PASSWORD: 'cafe1234'

  cafe-menu-service:
    build: ./menu-api
    image: hautrank2/cafe-menu:1
    environment:
      MONGODB_URI: 'mongodb://cafe-mongo-service:27017/cafe'
      AUTH_ADDRESS: 'cafe-auth-service:3000'
      MENU_IMAGE_FOLDER: '/app/data/images'
    volumes:
      - menu-images:/app/data/images

  cafe-order-service:
    build: ./order-api
    image: hautrank2/cafe-order:1
    environment:
      MONGODB_URI: 'mongodb://cafe-mongo-service:27017/cafe'
      AUTH_ADDRESS: 'cafe-auth-service:3000'

  shop-web:
    build: ./shop-web
    image: hautrank2/cafe-shop:1
    ports:
      - '8210:80'

  admin-web:
    build: ./admin-web
    image: hautrank2/cafe-admin:1
    ports:
      - '8211:80'

volumes:
  mongo-data:
  menu-images:
