apiVersion: v1
kind: Service
metadata:
  name: cafe-menu-service
spec:
  selector:
    app: menu
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-menu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu-api
          image: hautrank2/kub-cafe-menu:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: 'mongodb://cafe-mongo-service:27017/cafe'
            - name: AUTH_ADDRESS
              value: 'cafe-auth-service:3000'
            - name: MENU_IMAGE_FOLDER
              value: '/app/data/images'
          volumeMounts:
            - name: menu-images
              mountPath: /app/data/images
      volumes:
        - name: menu-images
          persistentVolumeClaim:
            claimName: cafe-menu-images-pvc
